# Error Func
def test_func4():
    return 10/0